# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa7812aca1f172708cadcd6b2e1b3f1556dbb60c6607e1a06d3a280d8a50a0f30f0b07d9bc7b1c4584c9fcca30e7dffb85c7f6ca169e327d4cf08005833d6d90

test:
  secret_key_base: e71ebe4e4a783dff836d24c0ab9d07ca43b91fd0dd846ab059df36f947635966c64ff81e814ad98a51c8796f48df66939aa955fbc1fd54dff86005e97e49a5d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
